# Basic NATS Server Configuration

server_name: "my-server"
host: 0.0.0.0
port: 4222

# Logging
debug: false
trace: false
logtime: true

# Limits
max_payload: 1MB
max_connections: 65536
ping_interval: 2m
write_deadline: 10s

# Authorization
authorization {
  token: "s3cr3t-t0ken"
}
