/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 32
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 29
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 4
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_include = 1,
  anon_sym_EQ = 2,
  anon_sym_COLON = 3,
  anon_sym_LBRACE = 4,
  anon_sym_COMMA = 5,
  anon_sym_RBRACE = 6,
  sym__quoted_string = 7,
  sym_number = 8,
  sym_variable_reference = 9,
  anon_sym_LBRACK = 10,
  anon_sym_RBRACK = 11,
  sym_bare_string = 12,
  sym_comment = 13,
  sym_identifier = 14,
  sym_boolean = 15,
  sym_source_file = 16,
  sym__statement = 17,
  sym_include_directive = 18,
  sym_block_definition = 19,
  sym_block = 20,
  sym_pair = 21,
  sym__value = 22,
  sym_string = 23,
  sym_array = 24,
  sym__array_value = 25,
  aux_sym_source_file_repeat1 = 26,
  aux_sym_block_repeat1 = 27,
  aux_sym_array_repeat1 = 28,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_include] = "include_keyword",
  [anon_sym_EQ] = "=",
  [anon_sym_COLON] = ":",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [sym__quoted_string] = "_quoted_string",
  [sym_number] = "number",
  [sym_variable_reference] = "variable_reference",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_bare_string] = "bare_string",
  [sym_comment] = "comment",
  [sym_identifier] = "identifier",
  [sym_boolean] = "boolean",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_include_directive] = "include_directive",
  [sym_block_definition] = "block_definition",
  [sym_block] = "block",
  [sym_pair] = "pair",
  [sym__value] = "_value",
  [sym_string] = "string",
  [sym_array] = "array",
  [sym__array_value] = "_array_value",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_include] = anon_sym_include,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym__quoted_string] = sym__quoted_string,
  [sym_number] = sym_number,
  [sym_variable_reference] = sym_variable_reference,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_bare_string] = sym_bare_string,
  [sym_comment] = sym_comment,
  [sym_identifier] = sym_identifier,
  [sym_boolean] = sym_boolean,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_include_directive] = sym_include_directive,
  [sym_block_definition] = sym_block_definition,
  [sym_block] = sym_block,
  [sym_pair] = sym_pair,
  [sym__value] = sym__value,
  [sym_string] = sym_string,
  [sym_array] = sym_array,
  [sym__array_value] = sym__array_value,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_include] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym__quoted_string] = {
    .visible = false,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_reference] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_bare_string] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_include_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_block_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym__array_value] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_key = 2,
  field_keyword = 3,
  field_name = 4,
  field_path = 5,
  field_value = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_key] = "key",
  [field_keyword] = "keyword",
  [field_name] = "name",
  [field_path] = "path",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 2},
  [4] = {.index = 6, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 1},
    {field_name, 0},
  [2] =
    {field_keyword, 0},
    {field_path, 1},
  [4] =
    {field_body, 2},
    {field_name, 0},
  [6] =
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 2,
  [6] = 4,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 8,
  [17] = 9,
  [18] = 18,
  [19] = 19,
  [20] = 10,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 15,
  [26] = 13,
  [27] = 14,
  [28] = 12,
  [29] = 29,
  [30] = 30,
  [31] = 31,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(14);
      ADVANCE_MAP(
        '"', 1,
        '$', 12,
        ',', 19,
        '-', 10,
        ':', 17,
        '=', 16,
        '[', 28,
        ']', 29,
        'i', 6,
        '{', 18,
        '}', 20,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '\\') ADVANCE(13);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == 'c') ADVANCE(5);
      END_STATE();
    case 3:
      if (lookahead == 'd') ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(8);
      END_STATE();
    case 6:
      if (lookahead == 'n') ADVANCE(2);
      END_STATE();
    case 7:
      if (lookahead == 's') ADVANCE(22);
      END_STATE();
    case 8:
      if (lookahead == 'u') ADVANCE(3);
      END_STATE();
    case 9:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(22);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 12:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 13:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_include);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym__quoted_string);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_number);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_number);
      ADVANCE_MAP(
        '.', 11,
        0xb5, 7,
        'G', 25,
        'g', 25,
        'K', 25,
        'k', 25,
        'M', 26,
        'm', 26,
        'N', 9,
        'n', 9,
        'T', 25,
        't', 25,
        'U', 9,
        'u', 9,
        'D', 22,
        'H', 22,
        'S', 22,
        'd', 22,
        'h', 22,
        's', 22,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_number);
      ADVANCE_MAP(
        0xb5, 7,
        'G', 25,
        'g', 25,
        'K', 25,
        'k', 25,
        'M', 26,
        'm', 26,
        'N', 9,
        'n', 9,
        'T', 25,
        't', 25,
        'U', 9,
        'u', 9,
        'D', 22,
        'H', 22,
        'S', 22,
        'd', 22,
        'h', 22,
        's', 22,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(22);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'B' ||
          lookahead == 'S' ||
          lookahead == 'b' ||
          lookahead == 's') ADVANCE(22);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_variable_reference);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 3},
  [3] = {.lex_state = 0, .external_lex_state = 3},
  [4] = {.lex_state = 0, .external_lex_state = 3},
  [5] = {.lex_state = 0, .external_lex_state = 3},
  [6] = {.lex_state = 0, .external_lex_state = 3},
  [7] = {.lex_state = 0, .external_lex_state = 4},
  [8] = {.lex_state = 0, .external_lex_state = 2},
  [9] = {.lex_state = 0, .external_lex_state = 2},
  [10] = {.lex_state = 0, .external_lex_state = 3},
  [11] = {.lex_state = 0, .external_lex_state = 2},
  [12] = {.lex_state = 0, .external_lex_state = 3},
  [13] = {.lex_state = 0, .external_lex_state = 3},
  [14] = {.lex_state = 0, .external_lex_state = 3},
  [15] = {.lex_state = 0, .external_lex_state = 3},
  [16] = {.lex_state = 0, .external_lex_state = 2},
  [17] = {.lex_state = 0, .external_lex_state = 2},
  [18] = {.lex_state = 0, .external_lex_state = 2},
  [19] = {.lex_state = 0, .external_lex_state = 2},
  [20] = {.lex_state = 0, .external_lex_state = 2},
  [21] = {.lex_state = 0, .external_lex_state = 2},
  [22] = {.lex_state = 0, .external_lex_state = 2},
  [23] = {.lex_state = 0, .external_lex_state = 2},
  [24] = {.lex_state = 0, .external_lex_state = 2},
  [25] = {.lex_state = 0, .external_lex_state = 2},
  [26] = {.lex_state = 0, .external_lex_state = 2},
  [27] = {.lex_state = 0, .external_lex_state = 2},
  [28] = {.lex_state = 0, .external_lex_state = 2},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0, .external_lex_state = 5},
  [31] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_include] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym__quoted_string] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_variable_reference] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_bare_string] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_boolean] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(31),
    [sym__statement] = STATE(19),
    [sym_include_directive] = STATE(19),
    [sym_block_definition] = STATE(19),
    [sym_pair] = STATE(19),
    [aux_sym_source_file_repeat1] = STATE(19),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_include] = ACTIONS(5),
    [sym_comment] = ACTIONS(7),
    [sym_identifier] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym_block] = STATE(4),
    [sym_string] = STATE(4),
    [sym_array] = STATE(4),
    [sym__array_value] = STATE(4),
    [aux_sym_array_repeat1] = STATE(4),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_COMMA] = ACTIONS(13),
    [sym__quoted_string] = ACTIONS(15),
    [sym_number] = ACTIONS(13),
    [sym_variable_reference] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_RBRACK] = ACTIONS(19),
    [sym_bare_string] = ACTIONS(15),
    [sym_comment] = ACTIONS(13),
    [sym_boolean] = ACTIONS(13),
  },
  [STATE(3)] = {
    [sym_block] = STATE(3),
    [sym_string] = STATE(3),
    [sym_array] = STATE(3),
    [sym__array_value] = STATE(3),
    [aux_sym_array_repeat1] = STATE(3),
    [anon_sym_LBRACE] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(24),
    [sym__quoted_string] = ACTIONS(27),
    [sym_number] = ACTIONS(24),
    [sym_variable_reference] = ACTIONS(24),
    [anon_sym_LBRACK] = ACTIONS(30),
    [anon_sym_RBRACK] = ACTIONS(33),
    [sym_bare_string] = ACTIONS(27),
    [sym_comment] = ACTIONS(24),
    [sym_boolean] = ACTIONS(24),
  },
  [STATE(4)] = {
    [sym_block] = STATE(3),
    [sym_string] = STATE(3),
    [sym_array] = STATE(3),
    [sym__array_value] = STATE(3),
    [aux_sym_array_repeat1] = STATE(3),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_COMMA] = ACTIONS(35),
    [sym__quoted_string] = ACTIONS(15),
    [sym_number] = ACTIONS(35),
    [sym_variable_reference] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_RBRACK] = ACTIONS(37),
    [sym_bare_string] = ACTIONS(15),
    [sym_comment] = ACTIONS(35),
    [sym_boolean] = ACTIONS(35),
  },
  [STATE(5)] = {
    [sym_block] = STATE(6),
    [sym_string] = STATE(6),
    [sym_array] = STATE(6),
    [sym__array_value] = STATE(6),
    [aux_sym_array_repeat1] = STATE(6),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_COMMA] = ACTIONS(39),
    [sym__quoted_string] = ACTIONS(15),
    [sym_number] = ACTIONS(39),
    [sym_variable_reference] = ACTIONS(39),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_RBRACK] = ACTIONS(41),
    [sym_bare_string] = ACTIONS(15),
    [sym_comment] = ACTIONS(39),
    [sym_boolean] = ACTIONS(39),
  },
  [STATE(6)] = {
    [sym_block] = STATE(3),
    [sym_string] = STATE(3),
    [sym_array] = STATE(3),
    [sym__array_value] = STATE(3),
    [aux_sym_array_repeat1] = STATE(3),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_COMMA] = ACTIONS(35),
    [sym__quoted_string] = ACTIONS(15),
    [sym_number] = ACTIONS(35),
    [sym_variable_reference] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_RBRACK] = ACTIONS(43),
    [sym_bare_string] = ACTIONS(15),
    [sym_comment] = ACTIONS(35),
    [sym_boolean] = ACTIONS(35),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(45), 1,
      anon_sym_LBRACE,
    ACTIONS(51), 1,
      anon_sym_LBRACK,
    STATE(23), 1,
      sym_block,
    ACTIONS(47), 2,
      sym_bare_string,
      sym__quoted_string,
    ACTIONS(49), 3,
      sym_boolean,
      sym_number,
      sym_variable_reference,
    STATE(24), 3,
      sym__value,
      sym_string,
      sym_array,
  [24] = 5,
    ACTIONS(5), 1,
      anon_sym_include,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(55), 1,
      anon_sym_RBRACE,
    ACTIONS(53), 2,
      sym_comment,
      anon_sym_COMMA,
    STATE(9), 5,
      sym__statement,
      sym_include_directive,
      sym_block_definition,
      sym_pair,
      aux_sym_block_repeat1,
  [45] = 5,
    ACTIONS(5), 1,
      anon_sym_include,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(59), 1,
      anon_sym_RBRACE,
    ACTIONS(57), 2,
      sym_comment,
      anon_sym_COMMA,
    STATE(11), 5,
      sym__statement,
      sym_include_directive,
      sym_block_definition,
      sym_pair,
      aux_sym_block_repeat1,
  [66] = 1,
    ACTIONS(61), 10,
      sym_bare_string,
      sym_comment,
      sym_boolean,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      sym__quoted_string,
      sym_number,
      sym_variable_reference,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [79] = 5,
    ACTIONS(63), 1,
      anon_sym_include,
    ACTIONS(69), 1,
      anon_sym_RBRACE,
    ACTIONS(71), 1,
      sym_identifier,
    ACTIONS(66), 2,
      sym_comment,
      anon_sym_COMMA,
    STATE(11), 5,
      sym__statement,
      sym_include_directive,
      sym_block_definition,
      sym_pair,
      aux_sym_block_repeat1,
  [100] = 1,
    ACTIONS(74), 10,
      sym_bare_string,
      sym_comment,
      sym_boolean,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      sym__quoted_string,
      sym_number,
      sym_variable_reference,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [113] = 1,
    ACTIONS(76), 10,
      sym_bare_string,
      sym_comment,
      sym_boolean,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      sym__quoted_string,
      sym_number,
      sym_variable_reference,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [126] = 1,
    ACTIONS(78), 10,
      sym_bare_string,
      sym_comment,
      sym_boolean,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      sym__quoted_string,
      sym_number,
      sym_variable_reference,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [139] = 1,
    ACTIONS(80), 10,
      sym_bare_string,
      sym_comment,
      sym_boolean,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      sym__quoted_string,
      sym_number,
      sym_variable_reference,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [152] = 5,
    ACTIONS(5), 1,
      anon_sym_include,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(84), 1,
      anon_sym_RBRACE,
    ACTIONS(82), 2,
      sym_comment,
      anon_sym_COMMA,
    STATE(17), 5,
      sym__statement,
      sym_include_directive,
      sym_block_definition,
      sym_pair,
      aux_sym_block_repeat1,
  [173] = 5,
    ACTIONS(5), 1,
      anon_sym_include,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(86), 1,
      anon_sym_RBRACE,
    ACTIONS(57), 2,
      sym_comment,
      anon_sym_COMMA,
    STATE(11), 5,
      sym__statement,
      sym_include_directive,
      sym_block_definition,
      sym_pair,
      aux_sym_block_repeat1,
  [194] = 5,
    ACTIONS(88), 1,
      ts_builtin_sym_end,
    ACTIONS(90), 1,
      anon_sym_include,
    ACTIONS(93), 1,
      sym_comment,
    ACTIONS(96), 1,
      sym_identifier,
    STATE(18), 5,
      sym__statement,
      sym_include_directive,
      sym_block_definition,
      sym_pair,
      aux_sym_source_file_repeat1,
  [214] = 5,
    ACTIONS(5), 1,
      anon_sym_include,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
    ACTIONS(101), 1,
      sym_comment,
    STATE(18), 5,
      sym__statement,
      sym_include_directive,
      sym_block_definition,
      sym_pair,
      aux_sym_source_file_repeat1,
  [234] = 1,
    ACTIONS(61), 6,
      sym_comment,
      sym_identifier,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [243] = 1,
    ACTIONS(103), 6,
      sym_comment,
      sym_identifier,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [252] = 1,
    ACTIONS(105), 6,
      sym_comment,
      sym_identifier,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [261] = 1,
    ACTIONS(107), 6,
      sym_comment,
      sym_identifier,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [270] = 1,
    ACTIONS(109), 6,
      sym_comment,
      sym_identifier,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [279] = 1,
    ACTIONS(80), 6,
      sym_comment,
      sym_identifier,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [288] = 1,
    ACTIONS(76), 6,
      sym_comment,
      sym_identifier,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [297] = 1,
    ACTIONS(78), 6,
      sym_comment,
      sym_identifier,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [306] = 1,
    ACTIONS(74), 6,
      sym_comment,
      sym_identifier,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [315] = 3,
    ACTIONS(45), 1,
      anon_sym_LBRACE,
    STATE(21), 1,
      sym_block,
    ACTIONS(111), 2,
      anon_sym_EQ,
      anon_sym_COLON,
  [326] = 2,
    STATE(22), 1,
      sym_string,
    ACTIONS(47), 2,
      sym_bare_string,
      sym__quoted_string,
  [334] = 1,
    ACTIONS(113), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 24,
  [SMALL_STATE(9)] = 45,
  [SMALL_STATE(10)] = 66,
  [SMALL_STATE(11)] = 79,
  [SMALL_STATE(12)] = 100,
  [SMALL_STATE(13)] = 113,
  [SMALL_STATE(14)] = 126,
  [SMALL_STATE(15)] = 139,
  [SMALL_STATE(16)] = 152,
  [SMALL_STATE(17)] = 173,
  [SMALL_STATE(18)] = 194,
  [SMALL_STATE(19)] = 214,
  [SMALL_STATE(20)] = 234,
  [SMALL_STATE(21)] = 243,
  [SMALL_STATE(22)] = 252,
  [SMALL_STATE(23)] = 261,
  [SMALL_STATE(24)] = 270,
  [SMALL_STATE(25)] = 279,
  [SMALL_STATE(26)] = 288,
  [SMALL_STATE(27)] = 297,
  [SMALL_STATE(28)] = 306,
  [SMALL_STATE(29)] = 315,
  [SMALL_STATE(30)] = 326,
  [SMALL_STATE(31)] = 334,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_definition, 2, 0, 1),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_directive, 2, 0, 2),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_definition, 3, 0, 3),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3, 0, 4),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [113] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_bare_string = 0,
  ts_external_token_comment = 1,
  ts_external_token_identifier = 2,
  ts_external_token_boolean = 3,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_bare_string] = sym_bare_string,
  [ts_external_token_comment] = sym_comment,
  [ts_external_token_identifier] = sym_identifier,
  [ts_external_token_boolean] = sym_boolean,
};

static const bool ts_external_scanner_states[6][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_bare_string] = true,
    [ts_external_token_comment] = true,
    [ts_external_token_identifier] = true,
    [ts_external_token_boolean] = true,
  },
  [2] = {
    [ts_external_token_comment] = true,
    [ts_external_token_identifier] = true,
  },
  [3] = {
    [ts_external_token_bare_string] = true,
    [ts_external_token_comment] = true,
    [ts_external_token_boolean] = true,
  },
  [4] = {
    [ts_external_token_bare_string] = true,
    [ts_external_token_boolean] = true,
  },
  [5] = {
    [ts_external_token_bare_string] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_nats_server_conf_external_scanner_create(void);
void tree_sitter_nats_server_conf_external_scanner_destroy(void *);
bool tree_sitter_nats_server_conf_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_nats_server_conf_external_scanner_serialize(void *, char *);
void tree_sitter_nats_server_conf_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_nats_server_conf(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_nats_server_conf_external_scanner_create,
      tree_sitter_nats_server_conf_external_scanner_destroy,
      tree_sitter_nats_server_conf_external_scanner_scan,
      tree_sitter_nats_server_conf_external_scanner_serialize,
      tree_sitter_nats_server_conf_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "nats_server_conf",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
